//! Emit LLVM IR from Spanda IR (SIR).
//!
//! Milestone 2 foundation: module/extern/robot signatures and stub bodies.
//! Full behavior lowering and `libspanda_rt` linking are not implemented yet.

use spanda_core::foundations::BridgeKind;
use spanda_core::sir::{SirExtern, SirFunction, SirProgram, SirVisibility};

pub fn emit_module_ir(sir: &SirProgram) -> String {
    let mut out = String::from("; Generated by spanda llvm-ir (SIR → LLVM Milestone 2)\n");
    out.push_str("target triple = \"x86_64-unknown-linux-gnu\"\n\n");

    if let Some(name) = &sir.module_name {
        out.push_str(&format!("; module {name}\n"));
    }
    for import in &sir.imports {
        out.push_str(&format!("; import {import}\n"));
    }
    if !sir.behavior_names.is_empty() {
        out.push_str(&format!("; behaviors: {}\n", sir.behavior_names.join(", ")));
    }
    for robot in &sir.robots {
        for behavior in &robot.behaviors {
            out.push_str(&format!(
                "; robot {} behavior {} ({} stmts)\n",
                robot.name, behavior.name, behavior.stmt_count
            ));
            out.push_str(&format!(
                "define void @spanda_robot_{}_{}() {{\n  ret void\n}}\n\n",
                robot.name, behavior.name
            ));
        }
        for task in &robot.task_names {
            out.push_str(&format!(
                "define void @spanda_robot_{}_task_{}() {{\n  ret void\n}}\n\n",
                robot.name, task
            ));
        }
    }
    out.push('\n');

    for ext in &sir.externs {
        out.push_str(&emit_extern_decl(ext));
    }
    for func in &sir.functions {
        if matches!(func.visibility, SirVisibility::Private) {
            continue;
        }
        out.push_str(&emit_function_stub(func));
    }
    for robot in &sir.robot_names {
        out.push_str(&format!(
            "define void @spanda_robot_{robot}_init() {{\n  ret void\n}}\n\n"
        ));
    }
    out.push_str("define i32 @spanda_main() {\n  ret i32 0\n}\n");
    out
}

fn llvm_type(type_name: &str) -> &'static str {
    match type_name {
        "Int" | "Float" | "Path" | "Scan" => "i32",
        "Bool" => "i1",
        "String" | "Char" | "Bytes" => "i8*",
        "Void" | "void" => "void",
        _ if type_name.starts_with("number(") => "double",
        _ => "i32",
    }
}

fn emit_extern_decl(ext: &SirExtern) -> String {
    let ret = llvm_type(&ext.return_type);
    let params: Vec<String> = ext
        .params
        .iter()
        .map(|p| format!("{} %{}", llvm_type(&p.type_name), p.name))
        .collect();
    let bridge = match ext.bridge {
        BridgeKind::Python => "python",
        BridgeKind::Cpp => "cpp",
        BridgeKind::Native => "native",
    };
    let sig = if ret == "void" {
        format!("declare void @{}({})", ext.name, params.join(", "))
    } else {
        format!("declare {} @{}({})", ret, ext.name, params.join(", "))
    };
    format!("; extern {bridge} {}\n{sig}\n\n", ext.name)
}

fn emit_function_stub(func: &SirFunction) -> String {
    let ret = llvm_type(&func.return_type);
    let params: Vec<String> = func
        .params
        .iter()
        .map(|p| format!("{} %{}", llvm_type(&p.type_name), p.name))
        .collect();
    if ret == "void" {
        format!(
            "define void @{}({}) {{\n  ret void\n}}\n\n",
            func.name,
            params.join(", ")
        )
    } else {
        let zero = if ret == "double" { "0.0" } else { "0" };
        format!(
            "define {} @{}({}) {{\n  ret {} {}\n}}\n\n",
            ret,
            func.name,
            params.join(", "),
            ret,
            zero
        )
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use spanda_core::{lexer, lower_to_sir, parser, types};

    #[test]
    fn emits_llvm_ir_for_module_functions() {
        let source = r#"
module demo;

export fn main() -> Int { return 1; }

extern python fn py_add(a: Int, b: Int) -> Int;

robot R {
  actuator wheels: DifferentialDrive;
  behavior run() { wheels.stop(); }
}
"#;
        let program = parser::parse(lexer::tokenize(source).unwrap()).unwrap();
        types::check(&program).unwrap();
        let sir = lower_to_sir(source).unwrap();
        let ir = emit_module_ir(&sir);
        assert!(ir.contains("define i32 @main("));
        assert!(ir.contains("declare i32 @py_add("));
        assert!(ir.contains("@spanda_robot_R_init"));
        assert!(ir.contains("@spanda_robot_R_run"));
        assert!(ir.contains("@spanda_main"));
    }
}
